import Navbar from '../_components/main/Navbar';
import OneProduct from './OneProduct';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function ProductPage() {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <OneProduct />
        {/* Продукт */}
      </body>
    </html>
  );
}
